#!/usr/bin/env bash

if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ( [ "$TRAVIS_BRANCH" = 'master' ] || [ "$TRAVIS_BRANCH" = 'devel' ] || [ ! -z "$TRAVIS_TAG" ] ); then
	mvn -P release install
else
	mvn install
fi
